### ISSUE TITLE
Https when building Docker

### ISSUE THREAD

**Issue by devnull556** [openboxes/openboxes-docker#12]
OpenBoxes isn't building correctly. I'm seeing the following in the terminal after issuing docker-compose up --build

grails_1  | 	SERVER ERROR: HTTPS Required url=http://repo1.maven.org/maven2/org/docx4j/docx4j/2.8.1/docx4j-2.8.1.pom

From what I've found, it loos like maven.org stopped responding to http requests, they must all be https only. 

Not being familiar with programming, I'm not sure where to make the appropriate changes.

**Comment by katsumi-valentin** [comment]
This is actually relatively easy to fix.

In the file under openboxes/grails-app/conf/BuildConfig.groovy there are a few lines pointing to the Maven repo:
mavenRepo "http://repo.grails.org/grails/plugins-releases/"
mavenRepo "http://repo.grails.org/grails/plugins/"
mavenRepo "http://repo.grails.org/grails/core/"
mavenRepo "http://oss.sonatype.org/content/repositories/snapshots/"

Just replace the "http" to "https" for each of them and it should build without errors.

**Comment by jmiranda** [comment]
@devnull556 Thanks for reporting this issue.

Thanks for helping out @katsumi-valentin. We fixed this in the develop branch in openboxes/openboxes a while back so I'm closing this ticket.
